### PR TITLE
Bump cabal CI to 9.6.1; bump bifunctors to latest

### PR DESCRIPTION
**Pull request by andreasabel**
@cydparser : Workflow run needs approval

### CODE REVIEW

**Comment by cydparser** [comment]
Thanks!

**Comment by ysangkok** [comment]
@cydparser Would it be possible to make a revision for the test suite now allowing bifunctors? It would address:

* https://github.com/commercialhaskell/stackage/issues/6910

**Comment by cydparser** [comment]
@ysangkok, there already is a revision for bifunctors: https://hackage.haskell.org/package/heist-1.1.1.1/revisions/

**Comment by ysangkok** [comment]
Oh, excellent! Sorry for the noise, I don't know how I missed that.

**Pull request merged**
