### PR TITLE
Bump the dependency on 'monad-control'.

### PR DESCRIPTION
**Pull request by 23Skidoo**

### CODE REVIEW

**Comment by hvr** [comment]
see also 721649658e1a84f359edaed36425bb308f143ca1

**Comment by mightybyte** [comment]
Just to make sure I'm clear on everything...it looks like I can just close this pull request, since @hvr's commit fixes the issue while maintaining support for the old monad-control?

**Comment by 23Skidoo** [comment]
@mightybyte Yes, but can you please cherry-pick the commit that bumps the test suite dependencies?

**Comment by mightybyte** [comment]
Ahh yes, I didn't notice that those were for the test suite.  I did one better and removed all test suite bounds that are duplicates of the bounds in the package.  This should make maintenance much easier.

**Pull request closed without merging**
