### PR TITLE
Minor changes to use pandoc 2

### PR DESCRIPTION
**Pull request by ludat**
mainly because of https://github.com/fpco/stackage/pull/3134

Not sure if we want to pin the version of pandoc

### CODE REVIEW

**Comment by mightybyte** [comment]
It appears this isn't passing the test suite.

**Comment by ludat** [comment]
That's because travis uses the packages from ubuntu to test and ubuntu repos have pandoc 1.19.

This is quite a breaking change since it'll break any program that uses the markdown side of heist (which I'd bet is quite small but still)

I can't think of a good way to solve this, if this were my project I'd simply remove the Markdown part of heist

**Comment by h-3-0** [comment]
How about this as a quick fix that doesn't break backwards compatibility:

- rename your patched version of `defaultPandocOptions` to `defaultPandoc2Options`
- add a `getPandocVersion` IO action that (by interrogating the environmental `pandoc`) returns one of three results: pandoc1, pandoc2 or unavailable
- in the test, switch `PandocOptions` and `markdownHtmlExpected` based on the pandoc version available; or skip if pandoc is unavailable (which would also address #98)

I might have a go at making such a PR today, since I've also encountered this problem.

**Comment by mightybyte** [comment]
It's definitely not acceptable to remove the markdown part of heist because users depend on it and we have a significant commitment to backwards compatibility.  The approach outlined by @h-3-0 sounds good to me.

**Comment by mightybyte** [comment]
I ended up completely removing the command line arguments heist was supplying to pandoc.  This makes it compatible with both 1.x and 2.x.  Thanks for working on this.

**Pull request closed without merging**
